FROM --platform=linux/amd64 ghost:5-alpine AS build

RUN apt-get update && apt-get install -y \
    python3 \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /opt/ai

COPY ai-bootstrap.js .



RUN npm init -y && \
    npm install --omit=dev --save applicationinsights && \
    npm install --omit=dev --save applicationinsights-native-metrics

FROM ghost:5-alpine

# Copy the Application Insights artifacts
COPY --from=build /opt/ai /opt/ai

# Copy custom routes.yaml into the Ghost configuration directory
COPY routes.yaml /var/lib/ghost/content/settings/routes.yaml


# Inject the scripts to to run before the main Node.Js application
ENV NODE_OPTIONS='--require /opt/ai/ai-bootstrap.js'