
FROM --platform=linux/amd64 ghost:latest AS build


WORKDIR /routing
COPY routes.yaml .



FROM --platform=linux/amd64 ghost:latest

RUN echo "Hello World!!"

# Copy the Application Insights artifacts
COPY --from=build /routing/routes.yaml /var/lib/ghost/content/settings/routes.yaml


# Fix permissions (Ghost runs as 'node' user)
RUN chown node:node /var/lib/ghost/content/settings/routes.yaml

# Run Ghost container

CMD ["node" "current/index.js"]

