version: '3.8'

services:
  ghost:
    build:
      context: .
    restart: always
    ports:
      - "2368:2368"
    environment:
      url: "http://localhost:2368"
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: rootpassword
      database__connection__database: ghostdb
    volumes:
      - ./content:/var/lib/ghost/content
      - ./routes.yaml:/var/lib/ghost/content/settings/routes.yaml 
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ghostdb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
